apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: webhook-system
spec:
  selector:
    app: resource-webhook
  ports:
    - name: https
      port: 443
      targetPort: 8443
